### ISSUE TITLE
Redis/Memcache purge behavior might lead to cache pollution

### ISSUE THREAD

**Issue by mlafeldt** [tedious/Stash#201]
When items are currently purged in Redis/Memcache, a path key will be created/incremented for each item. The key [has no TTL set](https://github.com/tedious/Stash/blob/dc04d658b75ecd38e3892af657bf6e28a7057909/src/Stash/Driver/Redis.php#L247), so the cache will get slowly polluted over time, at least when using the [volatile-lru strategy in Redis](http://redis.io/topics/lru-cache).

What do think about making the TTL of path keys configurable? This would make sense for us, since we know the maximum TTL of all items (and sub-items).

For Redis, the TTL could be passed [here](https://github.com/tedious/Stash/blob/dc04d658b75ecd38e3892af657bf6e28a7057909/src/Stash/Item.php#L187) from where it is passed through and eventually ends up being used [here](https://github.com/tedious/Stash/blob/dc04d658b75ecd38e3892af657bf6e28a7057909/src/Stash/Driver/Redis.php#L237).

Also, this might be added to other drivers as well.

What do you think?

/cc @s0enke

**Comment by tedivm** [comment]
Nice catch. I read through the redis documentation and want to quote a relevant point-

> volatile-lru: evict keys trying to remove the less recently used (LRU) keys first, but only among keys that have an expire set, in order to make space for the new data added.

What this says to me is that a key with no expiration will sit there forever. However, a key with an expiration- even if it's ridiculously far into the future- will fall into the LRU strategy. So if we set a default ttl of something like ten years for the keys and data around it everything will act as if it's a standard LRU system.

What I think needs to be done is a modification of the [store function](https://github.com/tedious/Stash/blob/dc04d658b75ecd38e3892af657bf6e28a7057909/src/Stash/Driver/Redis.php#L219) to make is so that if no expiration is passed the default one (which is so ridiculously far into the future that it's the equivalent of not putting a ttl in at all) gets used.

I don't believe this issue exists on memcache though, as it's LRU strategy ignores existing ttls (or the lack thereof).

**Comment by mlafeldt** [comment]
> What this says to me is that a key with no expiration will sit there forever. However, a key with an expiration- even if it's ridiculously far into the future- will fall into the LRU strategy. So if we set a default ttl of something like ten years for the keys and data around it everything will act as if it's a standard LRU system.

We (@s0enke and me) were actually referring to the `clear` method. It [sets/increments a version key](https://github.com/tedious/Stash/blob/master/src/Stash/Driver/Redis.php#L247) (without TTL), which results in a new key for each purge. Eventually the entire cache would consist of version keys when using Redis and volatile-lru (which is the default), because the "normal" keys would be evicted first.

We believe this could be worked around by using the `allkeys-lru` policy in Redis. Do you agree?
 
> What I think needs to be done is a modification of the store function to make is so that if no expiration is passed the default one (which is so ridiculously far into the future that it's the equivalent of not putting a ttl in at all) gets used.

We'd say an infinite TTL is actually a feature and as the developer can influence it, we see no reason to act upon this.

**Comment by mlafeldt** [comment]
FYI: we decided to use the `allkeys-lru policy` in our Redis databases, which seems to have fixed our problem.

You might want to add this information to the docs. :)
