### ISSUE TITLE
Debug Logging

### ISSUE THREAD

**Issue by alexbowers** [tedious/Stash#220]
A brief glance at the code shows that there is no debug level logging. only exception?

Is this correct, or am i missing something?

**Comment by tedivm** [comment]
Logging could very much be improved, but at the same time it needs to be balanced against performance. In programs that use Stash there are often hundreds of calls to cached objects, and each additional function call that gets added into something like Item creation then gets replicated hundreds of times.

Exception logging is easy and obvious so that's what I started with. Debug logging is a little more complicated because of the performance reasons and needs a more nuanced solution. I think having a DebugDriver that can be put in as a first layer in the Composite driver would be a perfect way to handle things, as it means that when debugging is turned off all of those extra calls simply disappear.

**Comment by alexbowers-tecmark** [comment]
Would it not be possible to have a debug flag set, then around each of the debug method calls have an if() around it, this adds a cost of O(1), which is negligible in terms of the system.
