### ISSUE TITLE
Code Improvement

### ISSUE THREAD

**Issue by alexbowers** [tedious/Stash#221]
Is there a reason that this:
https://github.com/tedious/Stash/blob/master/src/Stash/Pool.php#L83-L98

isn't like this?

``` php
public function setItemClass(ItemInterface $class)
    {
        $this->itemClass = $class;

        return true;
    }
```

**Comment by alexbowers** [comment]
Adding onto this, I don't think the class_exists is required either, since it will fail the initial argument.

**Comment by alexbowers** [comment]
PR made: https://github.com/tedious/Stash/pull/222

**Comment by SvenRtbg** [comment]
There is a reason: You are passing a string with the class name that should be instantiates inside the getItem method, not a concrete object. That string isn't the class itself, but is supposed to a) exist and b) implement the required interface. That's why the checks are there. 

However one could also pass an object here and check it with the type hint, and at the place of instantiation it would simply be cloned.

**Comment by alexbowers-tecmark** [comment]
I understand what the old code was doing; what I don't understand is why that way would be chosen.

Because, with this way, the code checks that the required implementation exists (ItemInterface); and by extension that the class exists (Can't have an interface without a class).

**Comment by SvenRtbg** [comment]
The reason is this line: https://github.com/tedious/Stash/blob/master/src/Stash/Pool.php#L138

    $item = new $this->itemClass();

Here the string with the class name to instantiate is used.

When you pass an object, this line would also have to change and clone the passed object, because you don't want to overwrite and return one single instance. 

This would allow using the magic function __clone() to intercept and do things instead of the current situation where there is no way to pass arguments to the constructor. I don't know if __clone() is the best idea, but it's possible.

**Comment by tedivm** [comment]
@SvenRtbg explained this really well, so I'm going to close this out.
