### ISSUE TITLE
psr/cache-implementation missing in composer.json: PSR-6 supported or not?

### ISSUE THREAD

**Issue by mindplay-dk** [tedious/Stash#233]
When browsing for [PSR-6 compliant packages on Packagist](https://packagist.org/providers/psr/cache-implementation), Stash does not list itself - that is, Stash does not state that it provides `psr/cache-implementation` in it's `composer.json` manifest.

Realizing that PSR-6 isn't final, I'm trying to select a PSR-6 compliant cache library for a project, and have my eyes on Stash as probably the most complete and well-tested caching library - but the lack of any manifest indication of commitment to PSR-6 has me a bit worried. Should I be?

I'd expect a cache library with a stated PSR-6 objective to at least [tag](https://packagist.org/search/?tags=psr-6) itself like other PSR-6 libraries, but I'd feel more warm and fuzzy about seeing the following lines in `composer.json`:

    "provide": {
        "psr/cache-implementation": "1.0.0"
    },
    "replace": {
        "psr/cache": "1.0.0"
    },

How come these are (still?) absent?

**Comment by tedivm** [comment]
PSR-6 is a draft- it's not even in review stage. Anyone linking off of it right now is insane, as it isn't done and is subject to change.

For the record, I'm one of the authors of PSR-6. As such I fully intend to have Stash support it when it is finalized.

**Comment by mindplay-dk** [comment]
I realize it's not done, but... Following the closest thing we have to a standard is insane? At this rate, it could be years before it's final.

How far off from PSR in its current state is Stash?

**Comment by tedivm** [comment]
Not that far off- it can probably be polished up in a release, with the major differences being things that are not quite agreed on with the FIG folks.

And yes, I think it's insane to publish a library that is going to be used by many people which may have API changes. I also think pegging agains "psr/cache 1.0.0" when it doesn't exist makes it's impossible to release quality software, since any changes on the interface suddenly break your library.

Don't get me wrong, I think having a semantic versioning scheme for these standards would be great, and would allow for things like a v0.9.0 release (not 100% defined or voted on but versioned in a way that people can count on to not break their libraries and available for easy testing and development). That's a whole other ball game though.

**Comment by mindplay-dk** [comment]
Okay, understood. So, assuming that Stash itself is stable and hasn't seen any breaking changes in recent time, why not tag it 1.0, to indicate that the API is stable? There's no saying how long it'll take before the PSR is finalized, and by then, it's likely a few minor breaking changes anyhow, so it's "2.0" to everyone currently using it anyhow.

My problem with 0.x releases, is semver permits every 0.x+1 release to contain breaking changes - even if 1.x is unmaintained immediately after 2.0 release, at least this is clearly indicated by version number changes... 0.x is sort of a weird limbo for semver, basically means "anything can change", which doesn't make consumers feel confident about that choice.

**Comment by tedivm** [comment]
The reason I'm not tagging it 1.0 is because I didn't want to lock it out of supporting PSR6 is there was something put into it that would make them incompatible. That being said I made this decision before I realized it was going to take several years to accomplish this.

**Comment by tedivm** [comment]
If you just track again a specific 0.X release you don't have to worry about backwards compatibility. Until I release v1.0.0 I'm using a 0.X.Y model, where any release that is not backwards incompatibility gets only a Y increment, and anything that is incompatible gets an X increment.
