### ISSUE TITLE
Add cache tagging support

### ISSUE THREAD

**Issue by andrerom** [tedious/Stash#245]
After some use of Stash now, working with FoSHttpCache and seeing what is coming in D8, I'm starting become rather convinced tags is a much better way to label cache then a Hierarchal primary key.

Why?
You can tag it with all possible meta data, and you can use them to normalize hierarchal information as well. And end result is that you can do much more fined grained cache clearing, avoiding cache slams by ending up to have to clear to much cache on complex operations.

eg:

data structure:

```
item {
  id: 55,
  parent: 33,
  type: 4,
}
```

cache keys/tags:
- item-55 _(primary)_
- parent-33
- type-4

clearing:
 clearing by "type-4" when type definition change clears all items of type: 4 as well as any cache for type 4 itself.
 clearing "item-55" and "parent-55" clear cache for id: 55 and all items that has been tagged as children of it.

_Side note: I guess it might imply exposing possibility on drivers to set/remove several keys at the same time to be able to do these things efficiently._

**Comment by tedivm** [comment]
The problem with all of my experiments with tagging has been performance. It seriously takes a hit due to the indexes that you have to maintain to associate keys with tags.

**Comment by andrerom** [comment]
Ok, I haven't looked under the hood, but aren't you forced to do something similar with Hierarchal keys?

**Comment by tedivm** [comment]
Similar but very different in scope, which makes it a bit more of a problem.

With hierarchal caching we're essentially putting things into folders. Each item in the folder only has one parent. The path to each items is generated using a node value for each parent- when we want to delete a key we simply increment the node, which makes the path fail to generate for it's previous keys. This operation is a very simple "add 1 to this field", and is very quick. Reading is a little slower as it has to pull the id from each parent recursively, but with a combination of in process caching of nodes and simply avoiding super long keys the extra calls are not that much.

Tagging is different though. Instead of it being a one to many relationship (one parent to many nodes), it's a many to many relationship (many tags to many items). This works fine in SQL based caches, but not so much in key value ones. If you look at other systems like Zend Cache you'll see they don't support tagging with memcache (or most of their backends) at all.

Now, it has been several years since I really explored this. I am not unwilling to do this, but I would need to see some proposals. One thought I had was actually using the Hierarchal as a tagging cache by creating paths out of the tags- this could be done by taking over the key creation, sorting tags alphabetically, and then otherwise treating them like a path.
