### ISSUE TITLE
PHP Warning:  mkdir(): File exists

### ISSUE THREAD

**Issue by kalenjordan** [tedious/Stash#281]
Just noticed this error got logged.  Is that a cache collission?

```
PHP Warning:  mkdir(): File exists in vendor/tedivm/stash/src/Stash/Driver/FileSystem.php on line 188
```

**Comment by tedivm** [comment]
This won't be a collision- what's happening is multiple processes are trying to create the needed directories, and due to a race condition one of the threads is creating the directory before the other process. This doesn't cause any issues beyond the occasional warning (which has been suppressed in the development branch).

**Comment by alexbowers** [comment]
As can be seen here, https://github.com/tedious/Stash/blob/master/src/Stash/Driver/FileSystem.php#L221, this error is suppressed.

Are you still getting this error? If so, it may be an issue with escalating your warnings to exceptions.
