### ISSUE TITLE
Random errors with Stash\Utilities::deleteRecursive()

### ISSUE THREAD

**Issue by andrerom** [tedious/Stash#359]
Actually had this with our behat test suite for the last year or two, it's random so haven't been able to pinpoint what the issue is. And re-reading the Stash code now I still can't quite make out what happens.

But my suggestion is that we simply add dependency on symfony/filesystem and use that instead in there to take care about recursive deletion, it's well tests on a range of file systems so there is good chance it will be able to be more solid for this.

Error we are getting is always in this form:
```
Warning: rmdir(app/cache/behat/stash/0fea6a13c52b4d47/25368f24b045ca84/c21f969b5f03d33d/43e04f8f136e7682/4a1c6be177996f9e/03934ae1c1c02ffc): Directory not empty in vendor/tedivm/stash/src/Stash/Utilities.php line 172 in vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php:85
  ╳  Stack trace:
  ╳  #0 [internal function]: Behat\Testwork\Call\Handler\RuntimeCallHandler->handleError(2, 'rmdir(...', 'vendor...', 172, Array)
  ╳  #1 vendor/tedivm/stash/src/Stash/Utilities.php(172): rmdir('app/ca...')
  ╳  #2 vendor/tedivm/stash/src/Stash/Driver/FileSystem.php(335): Stash\Utilities::deleteRecursive(Object(SplFileInfo), true)
  ╳  #3 vendor/tedivm/stash/src/Stash/Driver/Composite.php(163): Stash\Driver\FileSystem->clear(Array)
```
This was with `v0.14.2`, but we have had this issue for a while so I don't think any changes in `v0.14.x` is to blame.

**Comment by tedivm** [comment]
This may be a race condition- one process starts deleting and clears out the directory but another process adds new items in before that first process finishes. 

If that is the case (and I strongly believe it is) then a simple fix that would work immediately would be to rename the root file before beginning the cleanup operation. That way other processes can immediately write to the cache without causing problems.

**Comment by tedivm** [comment]
That being said I'm not opposed to switching to a more well polished solution such as the symfony/filesystem library, and it would be interesting to see if they already had a solution to this type of problem.

**Comment by mattford** [comment]
It appears the Symfony implementation combines error suppression operators with a second existence check, so it looks like this for a file delete for example:

`$success = (@unlink($path) && file_exists($path));`

**Comment by gggeek** [comment]
Confirm seeing the same issue randomly when using the Filesystem driver.
A cursory look at the code does indeed suggest that this is a race condition.

As much as I would like to trust other filesystem access libraries, I think that using rename-first instead of a double-check on file/directory suppression is a much better option. Renames are more or less the only FS option that is guaranteed to be atomic, and are widely used by libraries that have to deal with high concurrency writes (eg. file writes are always write-file-with-tmp-name-then-rename). Having said that: hod does the system cope with renaming a directory while a file is being added to it?
