### ISSUE TITLE
Add an ability to disable expiration time randomization. 

### ISSUE THREAD

**Issue by beeyev** [tedious/Stash#419]
The library has this code to slightly change the expiration time.
```php
$expirationDiff = rand(0, floor($cacheTime * .15));
$expiration -= $expirationDiff;
```
I know the reason, it's also discussed [here](https://github.com/tedious/Stash/issues/305).

Could you please add an ability to disable this feature when it's needed? 
Developers should be able to set precise TTL when they really want to do that.

**Comment by tedivm** [comment]
You can disable this at the Pool or Item level.

```php
$pool->setInvalidationMethod(Stash\Invalidation::NONE)
```

This can be done on the [item level](http://www.stashphp.com/Invalidation.html#none) as well. You may want to read through all the invalidation methods to see which one fits your needs most.

**Comment by beeyev** [comment]
I checked it, but this parameter does not change the behavior I mentioned.

[Here](https://github.com/tedious/Stash/blob/a2c9df16c77b13e1f90462f30597a772166eea8f/src/Stash/Item.php#L509)
```php
private function executeSet($data, $time)
    {
       ....

        // We need to be able to disable this part
        if ($cacheTime > 0) {
            $expirationDiff = rand(0, floor($cacheTime * .15));
            $expiration -= $expirationDiff;
        }
```

**Comment by haymaker** [comment]
For what it's worth, for anyone that did like me and puzzled over what seemed like random cache misses when (a) expecting an explicit expire time or (b) trying to set a short ttl:

I had a requirement to cache some data with a short, explicit ttl in order to ease unnecessary db calls, and determined the best way to accomplish this is by using `setTTL()`, `expiresAt()`, or `expiresAfter()` chained to `set()`. This bypasses the ttl randomization in `set()` and directly assigns the explicit TTL to the `$expiration` property.

````php
$ttl = 15; // 15 sec ttl

if($item->isMiss())
{
  // ...
  $data = updateData();
  
  $item->set(data)->expiresAfter($ttl);
  $pool->save($item);
}
````

Simple solution, but easy to overlook, especially when you don't realize that `set()` is going to subtract that random time from the TTL.
