### ISSUE TITLE
Unable to create file on windows

### ISSUE THREAD

**Issue by pwhelan** [tedious/Stash#61]
Stash v0.10.1 on windows fails with the following error.

> Message: touch() [function.touch]: Unable to create file C:\wamp\www\clickfortime.com\httpdocs/application//cache/1952a01898073d1e/561b9b4f2e42cbd7/a8b72798beb911ae/98c8c8907d45950a/b2eb734903575495/3b57a32e2841bda5/dc960c46c38bd16e/953d97cdeefdbc68/e9772a20f09b5d13/28a579892c11a4c8/cfcd208495d565ef/66e7dff9f98764da.php because Invalid argument

My best guess is because it is not using the correct path directory separator.

**Comment by xgathos** [comment]
There is a use case where this problem is not resolved: Right now we have an exception on windows systems thrown when the path is too long. But I discovered the problem on a linux system: CentOS on a vm (virtualbox / vagrant on windows host with shared drive) The vagrant synced folders are tied to windows limitations.

**Comment by gggeek** [comment]
@xgathos in my own experience, Vagrant synced folders have always been problematic: slow to use, prone to problems when dealing with symlinks, etc. I have always been much better off with storing the codebase within the VM itself and sharing it to the windows host via Samba (only downside: you need the VM to be on to access the files)
